language: python

install:
   - pip install awscli
   - export PATH=$PATH:$HOME/.local/bin

script:
   - aws s3 sync . s3://dylancsomra.com --delete
   - aws configure set preview.cloudfront true
   - aws cloudfront create-invalidation --distribution-id E3QR0MGHOF53C2 --paths "/*"
  

